// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.SuperClean.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "73E1557D-C113-46C5-95B5-50AFB47A7AAA";
        public const string Name = "Super Clean";
        public const string Description = @"Adds a 'Super Clean' option to the right click menu of the Solution and Project nodes of the Solution Explorer, to fully clear out the bin and obj folders for either all projects in the solution, or the specific project selected.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Coding with Calvin";
        public const string Tags = "bin,debug,folder,output";
    }
}
