// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.SuperClean.Vsix
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS-SuperClean";
        public const string Name = "Super Clean";
        public const string Description = @"Adds a 'Super Clean' option to the right click menu of the Solution and Project nodes of the Solution Explorer, to clear out the bin and obj folders for all, or selected, projects in the solution.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Coding With Calvin";
        public const string Tags = "bin,debug,folder,output";
    }
}
