// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodingWithCalvin.SuperClean
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageGuidString = "b9f1849b-9015-42a1-8d78-0b0bab1beb17";
        public static Guid PackageGuid = new Guid(PackageGuidString);

        public const string CommandSetGuidString = "2c1bb787-3f78-4c0e-a751-c43faf7b3356";
        public static Guid CommandSetGuid = new Guid(CommandSetGuidString);

        public const string IconGuidString = "e1543274-12ce-467c-84f8-2e5680b0bb98";
        public static Guid IconGuid = new Guid(IconGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SuperCleanCommandId = 0x0100;
        public const int BroomIcon = 0x0001;
    }
}