name: 'Build and Deploy'
  
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    tags-ignore:
      - "release/**"
  
jobs:
  Release-Build-and-Deploy: 
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1
    
    - name: 1. Versioning Release
      uses: CodingWithCalvin/GHA-VSVsixVersioner@v1
      with:
        extension-manifest-file: './src/CodingWithCalvin.SuperClean.Vsix/source.extension.vsixmanifest'
        extension-source-file: './src/CodingWithCalvin.SuperClean.Vsix/source.extension.cs'

    - name: 2. Bootstrapping NuGet Installer
      uses: nuget/setup-nuget@v1.1.1
    
    - name: 3. Restoring Packages
      run: nuget restore ./src/CodingWithCalvin.SuperClean.sln
    
    - name: 4. Building Project
      run: msbuild './src/CodingWithCalvin.SuperClean.Vsix/CodingWithCalvin.SuperClean.Vsix.csproj' /p:configuration='Release' /p:platform='x64'

    - name: 5. Publishing Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: './src/CodingWithCalvin.SuperClean.Vsix/bin/x64/Release/CodingWithCalvin.SuperClean.Vsix.vsix'
